server:
  port: 80
  servlet:
    path: /
spring:
  datasource:
      name: mydb  
      type: com.alibaba.druid.pool.DruidDataSource  
      username: root
      password: gener2017
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.3.20:3306/xql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong

sms:
  sid: 8a216da8762cb45701766eb24e8a1b02
  token: 27c57ffd34154812bee9e2d7348d68b0
  appid: 8a216da8762cb45701766eb24f5d1b09
  templateid: 808788