server:
  port: 8081
  servlet:
    path: /
spring:
  datasource:
      name: mydb  
      type: com.alibaba.druid.pool.DruidDataSource  
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong

    